

services:
  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    # ports:
    #   - 8000:8000
  
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tubearchivist.entrypoints=http"
      - "traefik.http.routers.tubearchivist.rule=Host(`tubearchivist.hughboi.cc`)"
      - "traefik.http.middlewares.tubearchivist-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.tubearchivist.middlewares=tubearchivist-https-redirect"
      - "traefik.http.routers.tubearchivist-secure.entrypoints=https"
      - "traefik.http.routers.tubearchivist-secure.rule=Host(`tubearchivist.hughboi.cc`)"
      - "traefik.http.routers.tubearchivist-secure.tls=true"
      - "traefik.http.routers.tubearchivist-secure.service=tubearchivist"
      - "traefik.http.services.tubearchivist.loadbalancer.server.port=8000"  # Assuming tubearchivist listens on port 80
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      - tubearchive
    volumes:
      - media:/youtube
      - cache:/cache
    environment:
      - ES_URL=http://archivist-es:9200     # needs protocol e.g. http and port
      - REDIS_HOST=archivist-redis          # don't add protocol
      - HOST_UID=1000
      - HOST_GID=1000
      - TA_HOST=tubearchivist.local         # set your host name
      - TA_USERNAME=tubearchivist           # your initial TA credentials
      - TA_PASSWORD=verysecret              # your initial TA credentials
      - ELASTIC_PASSWORD=verysecret         # set password for Elasticsearch
      - TZ=America/Denver               # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis/redis-stack-server
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    networks:
      - tubearchive
    volumes:
      - redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.16.0
    container_name: archivist-es
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=verysecret"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"
    networks:
      - tubearchive

volumes:
  media:
  cache:
  redis:
  es:

networks:
  proxy:
    external: true
  tubearchive:
