---
os: "linux"
arch: "amd64"

vip: 10.10.10.40

metallb_version: v0.13.12
lb_range: 10.10.10.110-10.10.10.120
lb_pool_name: first-pool

ansible_user: hughboi #<< this wasn't in his original script but i might need it
ansible_become: true
ansible_become_method: sudo
################################################################################
# options to change default values
# kube_vip_version: "v0.8.0"
# vip_interface: "eth0"
# rke2_version: "v1.29.4+rke2r1"
# rke2_install_dir: "/usr/local/bin"
