services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.baikal.entrypoints=http"
      - "traefik.http.routers.baikal.rule=Host(`baikal.hughboi.cc`)"
      - "traefik.http.middlewares.baikal-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.baikal.middlewares=baikal-https-redirect"
      - "traefik.http.routers.baikal-secure.entrypoints=https"
      - "traefik.http.routers.baikal-secure.rule=Host(`baikal.hughboi.cc`)"
      - "traefik.http.routers.baikal-secure.tls=true"
      - "traefik.http.routers.baikal-secure.service=baikal"
      - "traefik.http.services.baikal.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
      
networks:
  proxy:
    external: true

volumes:
  config:
  data:

