services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:v1.12.0
    container_name: mealie
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    deploy:
      resources:
        limits:
          memory: 1000M
    volumes:
      - mealie-data:/app/data/
    environment:
      ALLOW_SIGNUP: "false"
      PUID: 1000
      PGID: 1000
      TZ: America/Denver
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      BASE_URL: https://mealie.hughboi.cc
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mealie.entrypoints=http"
      - "traefik.http.routers.mealie.rule=Host(`mealie.hughboi.cc`)"
      - "traefik.http.middlewares.mealie-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mealie.middlewares=mealie-https-redirect"
      - "traefik.http.routers.mealie-secure.entrypoints=https"
      - "traefik.http.routers.mealie-secure.rule=Host(`mealie.hughboi.cc`)"
      - "traefik.http.routers.mealie-secure.tls=true"
      - "traefik.http.services.mealie.loadbalancer.server.port=9000"
      - "traefik.docker.network=proxy"
   networks:
      - proxy
      
volumes:
  mealie-data:


networks:
  proxy:
    external: true
