services:
  gatus:
    image: twinproduction/gatus:latest
    container_name: gatus
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    dns:
      - "10.10.10.9"  # specify bind9 so it can resolve hostnames.
      - "10.10.10.10"
    restart: unless-stopped
    ports:
      - "8074:8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER} # postgres user with access to the database
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} # postgres user password
      - POSTGRES_DB=${POSTGRES_DB} # this should be the name of your postgres database
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gatus.entrypoints=http"
      - "traefik.http.routers.gatus.rule=Host(`gatus.hughboi.cc`)"
      - "traefik.http.middlewares.gatus-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.gatus.middlewares=gatus-https-redirect"
      - "traefik.http.routers.gatus-secure.entrypoints=https"
      - "traefik.http.routers.gatus-secure.rule=Host(`gatus.hughboi.cc`)"
      - "traefik.http.routers.gatus-secure.tls=true"
      - "traefik.http.services.gatus.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    volumes:
      - ./config:/config
    networks:
      - proxy

networks:
  proxy:
    external: true
