services:
  gitlab:
    image: gitlab/gitlab-ce:17.2.4-ce.0
    container_name: gitlab
    hostname: 'gitlab'
    ports:
      - '8166:80'
      - '449:443'
      - '2424:22'
    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
    shm_size: '256m'
