services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    volumes:
      - upload:/usr/src/app/upload
      - /mnt/truenas-pics:/mnt/photos:ro #ro makes it read-only so I can't delete anything from Immich
    depends_on:
      - redis
    labels:
      - traefik.enable=true
      - traefik.http.routers.immich.entrypoints=http
      - traefik.http.routers.immich.rule=Host(`immich.hughboi.cc`)
      - traefik.http.middlewares.immich-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.immich.middlewares=immich-https-redirect
      - traefik.http.routers.immich-secure.entrypoints=https
      - traefik.http.routers.immich-secure.rule=Host(`immich.hughboi.cc`)
      - traefik.http.routers.immich-secure.tls=true
      - traefik.http.services.immich.loadbalancer.server.port=2283
      - traefik.docker.network=proxy
    networks:
      - proxy
      - immich

      
  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    restart: unless-stopped
    volumes:
      - model-cache:/cache
    networks:
      - immich


  database:
    container_name: immich_postgres
    image: tensorchord/pgvecto-rs:pg16-v0.3.0
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - immich
      
      
  redis:
    container_name: immich_redis
    image: redis:6.2-alpine
    restart: unless-stopped
    networks:
      - immich
      
      
networks:
  immich:
    driver: bridge
  proxy:
    external: true

volumes:
  upload:
  model-cache:
  pgdata:

