services:
  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    volumes:
      - speedtest-config:/config
    environment:
      - TZ=America/Denver
      - PGID=1000
      - PUID=1000
      - OOKLA_EULA_GDPR=true
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedtest-http.entrypoints=http"
      - "traefik.http.routers.speedtest-http.rule=Host(`speedtest.hughboi.cc`)"
      - "traefik.http.routers.speedtest-secure.entrypoints=https"
      - "traefik.http.routers.speedtest-secure.rule=Host(`speedtest.hughboi.cc`)"
      - "traefik.http.routers.speedtest-secure.tls=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"

networks:
  proxy:
    external: true

volumes:
  speedtest-config:
