---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hughboi-vip # change to your domain
  namespace: traefik # add to traefik namespace so it can use it (you DO NOT need it in each app namespace!!!)
spec:
  secretName: traefik-vip-tls # change to your secretname
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.hughboi.vip" # change to your domain
  dnsNames:
  - "*.hughboi.vip" # change to your domain
  - hughboi.vip # change to your domain
