# my global config
global:
  scrape_interval: 20s
  evaluation_interval: 30s
  body_size_limit: 300MB
  sample_limit: 10000
  target_limit: 100
  label_limit: 150
  label_name_length_limit: 5000
  label_value_length_limit: 5000
  # scrape_timeout is set to the global default (10s).

 # original
#  global:
#   scrape_interval: 15s
#   evaluation_interval: 30s
#   body_size_limit: 15MB
#   sample_limit: 1500
#   target_limit: 30
#   label_limit: 30
#   label_name_length_limit: 200
#   label_value_length_limit: 200
#   # scrape_timeout is set to the global default (10s). 

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['10.10.10.10:8073']
  
  # - job_name: 'node_exporter'
  #   static_configs:
  #     - targets: [ '10.10.10.10:9100']
