#
# The Firefly III Data Importer will ask you for the Firefly III URL and a "Client ID".
# You can generate the Client ID at http://localhost/profile (after registering)
# The Firefly III URL is: http://app:8080
#
# Other URL's will give 500 | Server Error
#

services:
  app:
    hostname: app
    container_name: firefly_iii_core
    image: fireflyiii/core:latest
    restart: unless-stopped
    logging:
      driver: loki
      options:
        loki-url: "https://loki.hughboi.cc/loki/api/v1/push"
        loki-retries: 2
        loki-max-backoff: 800ms
        loki-timeout: 1s
        keep-file: "true"
        mode: "non-blocking"
    networks:
      - firefly_iii
      - proxy
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly.entrypoints=http"
      - "traefik.http.routers.firefly.rule=Host(`firefly.hughboi.cc`)"
      - "traefik.http.middlewares.firefly-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.firefly.middlewares=firefly-https-redirect"
      - "traefik.http.routers.firefly-secure.entrypoints=https"
      - "traefik.http.routers.firefly-secure.rule=Host(`firefly.hughboi.cc`)"
      - "traefik.http.routers.firefly-secure.tls=true"
      - "traefik.http.routers.firefly-secure.service=firefly"
      - "traefik.http.services.firefly.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    depends_on:
      - db
  db:
    hostname: db
    container_name: firefly_iii_db
    image: mariadb:lts
    restart: always
    networks:
      - firefly_iii
    env_file: .db.env
    volumes:
      - firefly_iii_db:/var/lib/mysql

  importer:
    hostname: importer
    container_name: firefly_iii_importer
    image: fireflyiii/data-importer:latest
    restart: always
    networks:
      - firefly_iii
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firefly-importer.entrypoints=http"
      - "traefik.http.routers.firefly-importer.rule=Host(`firefly-importer.hughboi.cc`)"
      - "traefik.http.middlewares.firefly-importer-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.firefly-importer.middlewares=firefly-importer-https-redirect"
      - "traefik.http.routers.firefly-importer-secure.entrypoints=https"
      - "traefik.http.routers.firefly-importer-secure.rule=Host(`firefly-importer.hughboi.cc`)"
      - "traefik.http.routers.firefly-importer-secure.tls=true"
      - "traefik.http.routers.firefly-importer-secure.service=firefly-importer"
      - "traefik.http.services.firefly-importer.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    depends_on:
      - app
    env_file: .importer.env

  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "
      apk add tzdata
      && ln -s /usr/share/zoneinfo/${TZ} /etc/localtime
      | echo \"0 3 * * * wget -qO- http://app:8080/api/v1/cron/REPLACEME;echo\" 
      | crontab - 
      && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
volumes:
   firefly_iii_upload:
   firefly_iii_db:

networks:
  firefly_iii:
    driver: bridge
  proxy:
    external: true
